package com.geni.backend.trigger.core;

public enum TriggerType {
    GITHUB_ISSUE_OPENED,
    GITHUB_ISSUE_CLOSED,
    GITHUB_ISSUE_UPDATED,
    GITHUB_ISSUE_REOPENED,
    GITHUB_ISSUE_ASSIGNED,
    GITHUB_PR_OPENED,
    GITHUB_PR_MERGED,
    GITHUB_REVIEW_REQUESTED,
    GITHUB_REVIEW_SUBMITTED,
    GITHUB_PR_COMMENT_ADDED,
    GITHUB_PUSH,

    // GMAIL
    GMAIL_NEW_EMAIL,
}
