# docker-compose.yml
services:
  postgres:
    image: postgres:16
    container_name: geni-postgres
    environment:
      POSTGRES_DB: geni
      POSTGRES_USER: geni
      POSTGRES_PASSWORD: geni
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - geni_postgres_data:/var/lib/postgresql/data

  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    volumes:
      - ./vault/data:/vault/data
      - ./vault/vault-local.hcl:/vault/config/vault.hcl
    ports:
      - "8200:8200"
    command: server
    cap_add:
      - IPC_LOCK

volumes:
  geni_postgres_data:
  vault_data: