# docker-compose.yml
services:
  postgres:
    image: postgres:16
    container_name: geni-postgres
    environment:
      POSTGRES_DB: geni
      POSTGRES_USER: geni
      POSTGRES_PASSWORD: geni
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - geni_postgres_data:/var/lib/postgresql/data

  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_TOKEN : "myroot"
    cap_add:
      - IPC_LOCK
    command: server -dev

volumes:
  geni_postgres_data: