# application.properties

# ?? Database ??????????????????????????????????????????????????????????????????
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# ?? GitHub ????????????????????????????????????????????????????????????????????
geni.connectors.github.app-id=${GITHUB_APP_ID}
geni.connectors.github.app-name=${GITHUB_APP_NAME}
geni.connectors.github.client-id=${GITHUB_CLIENT_ID}
geni.connectors.github.webhook-secret=${GITHUB_WEBHOOK_SECRET}
geni.connectors.github.private-key-path=${GITHUB_PRIVATE_KEY_PATH}

# ?? Gmail ?????????????????????????????????????????????????????????????????????
geni.connectors.gmail.client-id=${GMAIL_CLIENT_ID}
geni.connectors.gmail.client-secret=${GMAIL_CLIENT_SECRET}
geni.connectors.gmail.redirect-uri=${GMAIL_REDIRECT_URI}
geni.connectors.gmail.global-topic-name=${GMAIL_GLOBAL_TOPIC_NAME}
geni.connectors.gmail.watch-url=${GMAIL_WATCH_URL}

secret.vault.uri=${VAULT_URL}
secret.vault.token=${VAULT_TOKEN}
