package com.geni.backend.workflow.core;

import com.geni.backend.workflow.enums.OnErrorStrategy;
import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * A node in the v1 workflow tree.
 *
 * v1 constraint: every step has at most ONE parent (tree, not general DAG).
 * Fan-out is supported — a parent can have many children.
 * Fan-in (merge) is v2.
 *
 * Execution order is derived at runtime by traversing parent_step_id links,
 * not by any stored order column.
 *
 * Edge from parent → this node is encoded directly on this row:
 *   parent_step_id  — who fires me (null = I am a root, fired by the trigger)
 *   edge_condition  — gate that must pass before I run (null = unconditional)
 *   edge_label      — human label shown in the visual builder ("Approved", etc.)
 */
@Entity
@Table(
        name = "workflow_steps"
//        indexes = {
//                // Executor query: "find all children of step X"
//                @Index(name = "idx_step_parent", columnList = "workflow_definition_id, parent_step_id"),
//                // Find all root steps for a workflow
//                @Index(name = "idx_step_roots",  columnList = "workflow_definition_id, parent_step_id",
//                        unique = false)
//        }
)
@Data
public class WorkflowStep {

    /**
     * System PK — auto-generated by Hibernate.
     * Used only for DB internals. Never referenced in field mappings.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /**
     * Client-supplied stable UUID.
     * Generated by the frontend before the request is sent.
     *
     * This is what field mapping expressions reference:
     *   "{{steps.<clientId>.output.field}}"
     *
     * Also what parentStepId points to — parent/child relationships
     * are wired by clientId, not by the system id.
     *
     * Immutable after creation (updatable = false).
     */
    @Column(name = "client_id", updatable = false, nullable = false)
    private UUID clientId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "workflow_definition_id", nullable = false)
    private WorkflowDefinition workflowDefinition;

    // ── Node identity ──────────────────────────────────────────

    @Column(nullable = false)
    private String name;

    // ── Tree structure (encodes the incoming edge) ─────────────

    /**
     * Parent step's UUID. NULL means this is a root step — it fires
     * directly when the trigger fires, with no predecessor step.
     *
     * A workflow can have multiple roots (all fire in parallel
     * immediately after the trigger).
     */
    @Column(name = "parent_step_id")
    private UUID parentStepId;

    /**
     * Condition that must evaluate to true before this step runs.
     * NULL = unconditional — always fires when parent completes.
     *
     * Stored as JSONB; deserialized into ConditionDefinition
     * (either StructuredCondition or SpelCondition).
     *
     * Evaluated at runtime against the ExecutionContext.
     * Validated (not evaluated) at save time.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "edge_condition", columnDefinition = "jsonb")
    private ConditionDefinition edgeCondition;

    /**
     * Human-readable label for the edge leading to this step.
     * Shown in the visual builder only — no runtime effect.
     * e.g. "Approved", "High value order", "On success"
     */
    @Column(name = "edge_label")
    private String edgeLabel;

    // ── Action ─────────────────────────────────────────────────

    /** Every v1 step is an ACTION — always required. */
    @Column(name = "action_definition_id", nullable = false)
    private String actionDefinitionId;

    /**
     * Which authenticated integration to use for this action.
     * May differ from the trigger's integration. It can be nullable if the action doesn't require an integration.
     */
    @Column(name = "integration_id")
    private String integrationId;

    /**
     * Input field mappings. Keys match ActionDefinition.inputSchema properties.
     * Values are template expressions resolved against ExecutionContext:
     *
     *   "{{trigger.email}}"
     *   "{{steps.3fa85f64-5717-4562-b3fc-2c963f66afa6.output.summary}}"
     *   "Hello {{trigger.name}}, your order is confirmed."
     *
     * Plain strings (no {{ }}) pass through as literals.
     * Step references must point to a strict ancestor of this step —
     * validated at save time, not at execution time.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "field_mappings", columnDefinition = "jsonb")
    private Map<String, String> fieldMappings = new HashMap<>();

    // ── Error handling ──────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(name = "on_error", nullable = false)
    private OnErrorStrategy onError = OnErrorStrategy.STOP;

    @Embedded
    private RetryConfig retryConfig;

}